[package]
name = "qdirstat"
version = "0.1.0"
authors = ["Quentin Lautischer <qlautischer@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="utils"
path="src/utils_lib/lib.rs"

[dependencies]
termcolor = "1.1"
console = "0.14"
dialoguer = "0.8"
